use crate::report::{Bucket, FileReport};
use std::collections::BTreeMap;

/// One file that landed in a cluster: its path + its own raw primary diagnostic
pub struct GapFile {
    pub path: String,
    pub raw: String,
}

pub struct Cause {
    /// The canonicalized message (identifiers/numbers replaced) — key AND title.
    pub canon: String,
    /// Files whose primary cause is this one (each GAP file appears exactly once).
    pub files: Vec<GapFile>,
    /// True when this is a sorobench multi-file limitation (`file not found`),
    /// not a solang language gap — flagged so it never inflates the real TODO.
    pub harness_noise: bool,
}

pub fn read_reports(text: &str) -> Result<Vec<FileReport>, String> {
    let mut out = Vec::new();
    for (i, line) in text.lines().enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        match serde_json::from_str::<FileReport>(line) {
            Ok(r) => out.push(r),
            Err(e) => return Err(format!("line {}: {e}", i + 1)),
        }
    }
    Ok(out)
}

pub fn atoms(detail: &str) -> Vec<String> {
    let body = detail.strip_prefix("solang:").unwrap_or(detail).trim();
    let mut seen = Vec::new();
    for part in body.split(';') {
        let a = part.trim();
        if !a.is_empty() && !seen.iter().any(|s| s == a) {
            seen.push(a.to_string());
        }
    }
    seen
}

/// Canonicalize one atom into a cluster key: `'quoted'` and `` `quoted` `` spans
/// collapse to `'X'`/`` `X` ``, and any run of ASCII digits collapses to `N`, so
/// `conversion to bytes1 from uint32` and `conversion to bytes3 from uint32`
/// (etc.) land in the same bucket. Regex-free to keep the standalone build lean.
pub fn canonicalize(atom: &str) -> String {
    let mut out = String::with_capacity(atom.len());
    let mut chars = atom.chars().peekable();
    while let Some(c) = chars.next() {
        match c {
            '\'' | '`' => {
                // Collapse the whole quoted span to the same delimiter + X.
                out.push(c);
                out.push('X');
                for q in chars.by_ref() {
                    if q == c {
                        break;
                    }
                }
                out.push(c);
            }
            d if d.is_ascii_digit() => {
                out.push('N');
                while matches!(chars.peek(), Some(q) if q.is_ascii_digit()) {
                    chars.next();
                }
            }
            _ => out.push(c),
        }
    }
    out
}

const HARNESS_MARKER: &str = "file not found";
/// The single canonical key every multi-file test collapses under.
const HARNESS_CANON: &str =
    "file not found 'X' (multi-file import — sorobench limitation, not a solang gap)";

/// Cluster the GAP files of a run by primary root cause. Every `Bucket::Gap`
/// report appears under exactly one [`Cause`]; the returned list is sorted by
/// file count (desc), then by canonical key. Non-GAP reports are ignored.
pub fn cluster(reports: &[FileReport]) -> Vec<Cause> {
    let mut map: BTreeMap<String, Cause> = BTreeMap::new();

    for r in reports.iter().filter(|r| r.bucket == Bucket::Gap) {
        let parts = atoms(&r.detail);

        // A `file not found` anywhere means the true root is a missing imported
        // source (the rest is cascade) — group the whole file as harness noise.
        let (canon, raw, harness_noise) =
            if let Some(nf) = parts.iter().find(|a| a.contains(HARNESS_MARKER)) {
                (HARNESS_CANON.to_string(), nf.clone(), true)
            } else {
                match parts.first() {
                    Some(primary) => (canonicalize(primary), primary.clone(), false),
                    None => ("(no detail)".to_string(), "(no detail)".to_string(), false),
                }
            };

        let entry = map.entry(canon.clone()).or_insert_with(|| Cause {
            canon,
            files: Vec::new(),
            harness_noise,
        });
        entry.files.push(GapFile {
            path: r.path.clone(),
            raw,
        });
    }

    let mut causes: Vec<Cause> = map.into_values().collect();
    for c in &mut causes {
        c.files.sort_by(|a, b| a.path.cmp(&b.path));
    }
    causes.sort_by(|a, b| {
        b.files
            .len()
            .cmp(&a.files.len())
            .then(a.canon.cmp(&b.canon))
    });
    causes
}

pub fn render_markdown(causes: &[Cause], source: &str) -> String {
    use std::fmt::Write;
    let mut s = String::new();

    let total: usize = causes.iter().map(|c| c.files.len()).sum();
    let noise: usize = causes
        .iter()
        .filter(|c| c.harness_noise)
        .map(|c| c.files.len())
        .sum();
    let real_causes = causes.iter().filter(|c| !c.harness_noise).count();

    let _ = writeln!(s, "# sorobench — solang gap ledger\n");
    let _ = writeln!(s, "Generated by `sorobench gaps` from `{source}`.\n");
    let _ = writeln!(
        s,
        "A **GAP** is a file solang rejected with a *clean* compile error on portable \
         source — not filtered (no EVM-only feature), not a crash, not a timeout. \
         Soroban can express these, so each is a solang TODO.\n"
    );
    let _ = writeln!(s, "- GAP files: **{total}**");
    let _ = writeln!(s, "- distinct solang root causes: **{real_causes}**");
    let _ = writeln!(
        s,
        "- multi-file-import files (sorobench limitation, not a solang gap): **{noise}**\n"
    );

    let _ = writeln!(s, "## Major gaps (by file count)\n");
    let _ = writeln!(s, "| files | root cause | kind |");
    let _ = writeln!(s, "|---:|---|---|");
    for c in causes {
        let kind = if c.harness_noise { "harness" } else { "solang" };
        let _ = writeln!(
            s,
            "| {} | {} | {} |",
            c.files.len(),
            md_cell(&c.canon),
            kind
        );
    }
    let _ = writeln!(s);

    for c in causes {
        let tag = if c.harness_noise {
            " *(sorobench multi-file limitation — not a solang gap)*"
        } else {
            ""
        };
        let _ = writeln!(s, "## {} — {} file(s){tag}\n", c.canon, c.files.len());
        for f in &c.files {
            if f.raw == c.canon {
                let _ = writeln!(s, "- `{}`", f.path);
            } else {
                let _ = writeln!(s, "- `{}` — {}", f.path, f.raw);
            }
        }
        let _ = writeln!(s);
    }

    s
}

fn md_cell(msg: &str) -> String {
    msg.replace('|', "\\|").replace('\n', " ")
}
