use crate::report::{Bucket, FileReport};
use std::collections::BTreeMap;

/// One file that landed in a cluster: its path + its own raw primary diagnostic.
pub struct LedgerFile {
    pub path: String,
    pub raw: String,
}

pub struct Cause {
    /// The canonicalized message (identifiers/numbers replaced) — key AND title.
    pub canon: String,
    /// Files whose primary cause is this one (each appears exactly once).
    pub files: Vec<LedgerFile>,
    /// True when this is a sorobench-side limitation, not a solang bug — flagged
    /// so it never inflates the real count.
    pub harness_noise: bool,
}

pub fn read_reports(text: &str) -> Result<Vec<FileReport>, String> {
    let mut out = Vec::new();
    for (i, line) in text.lines().enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        match serde_json::from_str::<FileReport>(line) {
            Ok(r) => out.push(r),
            Err(e) => return Err(format!("line {}: {e}", i + 1)),
        }
    }
    Ok(out)
}

pub fn canonicalize(msg: &str, collapse_quoted: bool) -> String {
    let mut out = String::with_capacity(msg.len());
    let mut chars = msg.chars().peekable();
    while let Some(c) = chars.next() {
        match c {
            '\'' | '`' => {
                out.push(c);
                if collapse_quoted {
                    // Drop the quoted run, leaving a single placeholder: `'X'`.
                    out.push('X');
                    for q in chars.by_ref() {
                        if q == c {
                            break;
                        }
                    }
                    out.push(c);
                } else {
                    // Keep the quoted text (and its closing quote) verbatim.
                    for q in chars.by_ref() {
                        out.push(q);
                        if q == c {
                            break;
                        }
                    }
                }
            }
            d if d.is_ascii_digit() => {
                out.push('N');
                while matches!(chars.peek(), Some(q) if q.is_ascii_digit()) {
                    chars.next();
                }
            }
            _ => out.push(c),
        }
    }
    out
}

/// Cluster one `bucket` of a run. `classify` maps a file's `detail` to its
/// `(cluster key / title, this file's raw diagnostic, harness_noise)` triple.
pub fn cluster(
    reports: &[FileReport],
    bucket: Bucket,
    classify: impl Fn(&str) -> (String, String, bool),
) -> Vec<Cause> {
    let mut map: BTreeMap<String, Cause> = BTreeMap::new();

    for r in reports.iter().filter(|r| r.bucket == bucket) {
        let (canon, raw, harness_noise) = classify(&r.detail);
        let entry = map.entry(canon.clone()).or_insert_with(|| Cause {
            canon,
            files: Vec::new(),
            harness_noise,
        });
        entry.files.push(LedgerFile {
            path: r.path.clone(),
            raw,
        });
    }

    let mut causes: Vec<Cause> = map.into_values().collect();
    for c in &mut causes {
        c.files.sort_by(|a, b| a.path.cmp(&b.path));
    }
    causes.sort_by(|a, b| {
        b.files
            .len()
            .cmp(&a.files.len())
            .then(a.canon.cmp(&b.canon))
    });
    causes
}

/// The bucket-specific prose and labels that vary between ledgers. Everything
/// else in [`render_markdown`] is shared.
pub struct LedgerText {
    /// Ledger name in the H1 — rendered as `# sorobench — {title} ledger`.
    pub title: &'static str,
    /// Subcommand that produced it — `Generated by `sorobench {command}``.
    pub command: &'static str,
    /// One-paragraph definition of the bucket (no trailing newline).
    pub blurb: &'static str,
    /// Label for the total-files stat, e.g. `GAP files`.
    pub total_label: &'static str,
    /// Label for the distinct-causes stat, e.g. `distinct solang root causes`.
    pub causes_label: &'static str,
    /// Label for the harness-noise stat.
    pub noise_label: &'static str,
    /// Heading for the summary table, e.g. `Major gaps (by file count)`.
    pub table_heading: &'static str,
    /// Right-hand table column header, e.g. `root cause`.
    pub cause_col: &'static str,
    /// Suffix appended to a harness-noise cause's heading.
    pub noise_tag: &'static str,
}

pub fn render_markdown(causes: &[Cause], source: &str, t: &LedgerText) -> String {
    use std::fmt::Write;
    let mut s = String::new();

    let total: usize = causes.iter().map(|c| c.files.len()).sum();
    let noise: usize = causes
        .iter()
        .filter(|c| c.harness_noise)
        .map(|c| c.files.len())
        .sum();
    let real_causes = causes.iter().filter(|c| !c.harness_noise).count();

    let _ = writeln!(s, "# sorobench — {} ledger\n", t.title);
    let _ = writeln!(
        s,
        "Generated by `sorobench {}` from `{source}`.\n",
        t.command
    );
    let _ = writeln!(s, "{}\n", t.blurb);
    let _ = writeln!(s, "- {}: **{total}**", t.total_label);
    let _ = writeln!(s, "- {}: **{real_causes}**", t.causes_label);
    let _ = writeln!(s, "- {}: **{noise}**\n", t.noise_label);

    let _ = writeln!(s, "## {}\n", t.table_heading);
    let _ = writeln!(s, "| files | {} |", t.cause_col);
    let _ = writeln!(s, "|---:|---|");
    for c in causes {
        let _ = writeln!(s, "| {} | {} |", c.files.len(), md_cell(&c.canon));
    }
    let _ = writeln!(s);

    for c in causes {
        let tag = if c.harness_noise { t.noise_tag } else { "" };
        let _ = writeln!(s, "## {} — {} file(s){tag}\n", c.canon, c.files.len());
        let _ = writeln!(s, "<details><summary>{} file(s)</summary>\n", c.files.len());
        for f in &c.files {
            if f.raw == c.canon {
                let _ = writeln!(s, "- `{}`", f.path);
            } else {
                let _ = writeln!(s, "- `{}` — {}", f.path, f.raw);
            }
        }
        let _ = writeln!(s, "\n</details>\n");
    }

    s
}

fn md_cell(msg: &str) -> String {
    msg.replace('|', "\\|").replace('\n', " ")
}
